version: "3.3"
services:
  vpn:
    container_name: vpn
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=1E1odJ9ENrOxeXoA
      - OPENVPN_PASSWORD=PFT02ezwSEqKb58pjY2N1I5hef0aleEn
      - SERVER_COUNTRIES=United States
        #  - SERVER_COUNTRIES=Netherlands
      - FREE_ONLY=on
    networks:
      - mynetwork
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
      - "5842:5842"
      - "5841:5841"
      - "80:80"
      - "8080:8080"
      - "5000:5000"
      - 27017:27017
      - "32:32"
    restart: "unless-stopped"
  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission
    network_mode: service:vpn
    environment:
      - USER=admin
      - PASS=nimdatx
    restart: "unless-stopped"
  app:
    build: .
    command: bash start.sh
    restart: on-failure  
    network_mode: service:vpn
    volumes:
      - app-data:/app
volumes:
  app-data:
networks:
  mynetwork:                                 
    external: true
